package com.sparkdoctor.model;

import java.util.List;

public record StageAnalysis(
        int id,
        String name,
        Integer taskCount,
        int completedTasks,
        Long minTaskDurationMillis,
        Long maxTaskDurationMillis,
        Long avgTaskDurationMillis,
        Long medianTaskDurationMillis,
        Long p95TaskDurationMillis,
        Long p99TaskDurationMillis,
        List<Long> taskDurationMillis,
        int failedTaskAttempts,
        long failedTaskAttemptDurationMillis,
        List<String> failedTaskAttemptReasons,
        List<WorkerSummary> executorSummaries,
        List<WorkerSummary> hostSummaries,
        long shuffleReadBytes,
        Long maxTaskShuffleReadBytes,
        Long medianTaskShuffleReadBytes,
        Long p95TaskShuffleReadBytes,
        Long p99TaskShuffleReadBytes,
        List<Long> taskShuffleReadBytes,
        long memoryBytesSpilled,
        long diskBytesSpilled,
        Long maxTaskMemoryBytesSpilled,
        Long maxTaskDiskBytesSpilled,
        Long medianTaskMemoryBytesSpilled,
        Long p95TaskMemoryBytesSpilled,
        Long p99TaskMemoryBytesSpilled,
        List<Long> taskMemoryBytesSpilled,
        Long medianTaskDiskBytesSpilled,
        Long p95TaskDiskBytesSpilled,
        Long p99TaskDiskBytesSpilled,
        List<Long> taskDiskBytesSpilled) {
    public StageAnalysis {
        taskDurationMillis = taskDurationMillis == null ? List.of() : List.copyOf(taskDurationMillis);
        failedTaskAttemptReasons = failedTaskAttemptReasons == null ? List.of() : List.copyOf(failedTaskAttemptReasons);
        executorSummaries = executorSummaries == null ? List.of() : List.copyOf(executorSummaries);
        hostSummaries = hostSummaries == null ? List.of() : List.copyOf(hostSummaries);
        taskShuffleReadBytes = taskShuffleReadBytes == null ? List.of() : List.copyOf(taskShuffleReadBytes);
        taskMemoryBytesSpilled = taskMemoryBytesSpilled == null ? List.of() : List.copyOf(taskMemoryBytesSpilled);
        taskDiskBytesSpilled = taskDiskBytesSpilled == null ? List.of() : List.copyOf(taskDiskBytesSpilled);
    }

    public StageAnalysis(
            int id,
            String name,
            Integer taskCount,
            int completedTasks,
            Long minTaskDurationMillis,
            Long maxTaskDurationMillis,
            Long avgTaskDurationMillis,
            long shuffleReadBytes,
            Long maxTaskShuffleReadBytes,
            Long medianTaskShuffleReadBytes,
            Long p95TaskShuffleReadBytes,
            Long p99TaskShuffleReadBytes,
            List<Long> taskShuffleReadBytes,
            long memoryBytesSpilled,
            long diskBytesSpilled,
            Long maxTaskMemoryBytesSpilled,
            Long maxTaskDiskBytesSpilled) {
        this(
                id,
                name,
                taskCount,
                completedTasks,
                minTaskDurationMillis,
                maxTaskDurationMillis,
                avgTaskDurationMillis,
                null,
                null,
                null,
                List.of(),
                0,
                0L,
                List.of(),
                List.of(),
                List.of(),
                shuffleReadBytes,
                maxTaskShuffleReadBytes,
                medianTaskShuffleReadBytes,
                p95TaskShuffleReadBytes,
                p99TaskShuffleReadBytes,
                taskShuffleReadBytes,
                memoryBytesSpilled,
                diskBytesSpilled,
                maxTaskMemoryBytesSpilled,
                maxTaskDiskBytesSpilled,
                null,
                null,
                null,
                List.of(),
                null,
                null,
                null,
                List.of());
    }

    public StageAnalysis(
            int id,
            String name,
            Integer taskCount,
            int completedTasks,
            Long minTaskDurationMillis,
            Long maxTaskDurationMillis,
            Long avgTaskDurationMillis,
            Long medianTaskDurationMillis,
            Long p95TaskDurationMillis,
            Long p99TaskDurationMillis,
            List<Long> taskDurationMillis,
            int failedTaskAttempts,
            long failedTaskAttemptDurationMillis,
            List<String> failedTaskAttemptReasons,
            List<WorkerSummary> executorSummaries,
            List<WorkerSummary> hostSummaries,
            long shuffleReadBytes,
            Long maxTaskShuffleReadBytes,
            Long medianTaskShuffleReadBytes,
            Long p95TaskShuffleReadBytes,
            Long p99TaskShuffleReadBytes,
            List<Long> taskShuffleReadBytes,
            long memoryBytesSpilled,
            long diskBytesSpilled,
            Long maxTaskMemoryBytesSpilled,
            Long maxTaskDiskBytesSpilled) {
        this(
                id,
                name,
                taskCount,
                completedTasks,
                minTaskDurationMillis,
                maxTaskDurationMillis,
                avgTaskDurationMillis,
                medianTaskDurationMillis,
                p95TaskDurationMillis,
                p99TaskDurationMillis,
                taskDurationMillis,
                failedTaskAttempts,
                failedTaskAttemptDurationMillis,
                failedTaskAttemptReasons,
                executorSummaries,
                hostSummaries,
                shuffleReadBytes,
                maxTaskShuffleReadBytes,
                medianTaskShuffleReadBytes,
                p95TaskShuffleReadBytes,
                p99TaskShuffleReadBytes,
                taskShuffleReadBytes,
                memoryBytesSpilled,
                diskBytesSpilled,
                maxTaskMemoryBytesSpilled,
                maxTaskDiskBytesSpilled,
                null,
                null,
                null,
                List.of(),
                null,
                null,
                null,
                List.of());
    }

    public StageAnalysis(
            int id,
            String name,
            Integer taskCount,
            int completedTasks,
            Long minTaskDurationMillis,
            Long maxTaskDurationMillis,
            Long avgTaskDurationMillis,
            Long medianTaskDurationMillis,
            Long p95TaskDurationMillis,
            Long p99TaskDurationMillis,
            List<Long> taskDurationMillis,
            long shuffleReadBytes,
            Long maxTaskShuffleReadBytes,
            Long medianTaskShuffleReadBytes,
            Long p95TaskShuffleReadBytes,
            Long p99TaskShuffleReadBytes,
            List<Long> taskShuffleReadBytes,
            long memoryBytesSpilled,
            long diskBytesSpilled,
            Long maxTaskMemoryBytesSpilled,
            Long maxTaskDiskBytesSpilled) {
        this(
                id,
                name,
                taskCount,
                completedTasks,
                minTaskDurationMillis,
                maxTaskDurationMillis,
                avgTaskDurationMillis,
                medianTaskDurationMillis,
                p95TaskDurationMillis,
                p99TaskDurationMillis,
                taskDurationMillis,
                0,
                0L,
                List.of(),
                List.of(),
                List.of(),
                shuffleReadBytes,
                maxTaskShuffleReadBytes,
                medianTaskShuffleReadBytes,
                p95TaskShuffleReadBytes,
                p99TaskShuffleReadBytes,
                taskShuffleReadBytes,
                memoryBytesSpilled,
                diskBytesSpilled,
                maxTaskMemoryBytesSpilled,
                maxTaskDiskBytesSpilled);
    }

    public StageAnalysis(
            int id,
            String name,
            Integer taskCount,
            int completedTasks,
            Long minTaskDurationMillis,
            Long maxTaskDurationMillis,
            Long avgTaskDurationMillis,
            Long medianTaskDurationMillis,
            Long p95TaskDurationMillis,
            Long p99TaskDurationMillis,
            List<Long> taskDurationMillis,
            int failedTaskAttempts,
            long failedTaskAttemptDurationMillis,
            List<String> failedTaskAttemptReasons,
            long shuffleReadBytes,
            Long maxTaskShuffleReadBytes,
            Long medianTaskShuffleReadBytes,
            Long p95TaskShuffleReadBytes,
            Long p99TaskShuffleReadBytes,
            List<Long> taskShuffleReadBytes,
            long memoryBytesSpilled,
            long diskBytesSpilled,
            Long maxTaskMemoryBytesSpilled,
            Long maxTaskDiskBytesSpilled) {
        this(
                id,
                name,
                taskCount,
                completedTasks,
                minTaskDurationMillis,
                maxTaskDurationMillis,
                avgTaskDurationMillis,
                medianTaskDurationMillis,
                p95TaskDurationMillis,
                p99TaskDurationMillis,
                taskDurationMillis,
                failedTaskAttempts,
                failedTaskAttemptDurationMillis,
                failedTaskAttemptReasons,
                List.of(),
                List.of(),
                shuffleReadBytes,
                maxTaskShuffleReadBytes,
                medianTaskShuffleReadBytes,
                p95TaskShuffleReadBytes,
                p99TaskShuffleReadBytes,
                taskShuffleReadBytes,
                memoryBytesSpilled,
                diskBytesSpilled,
                maxTaskMemoryBytesSpilled,
                maxTaskDiskBytesSpilled,
                null,
                null,
                null,
                List.of(),
                null,
                null,
                null,
                List.of());
    }

    public StageAnalysis(
            int id,
            String name,
            Integer taskCount,
            int completedTasks,
            Long minTaskDurationMillis,
            Long maxTaskDurationMillis,
            Long avgTaskDurationMillis,
            Long medianTaskDurationMillis,
            Long p95TaskDurationMillis,
            Long p99TaskDurationMillis,
            List<Long> taskDurationMillis,
            long shuffleReadBytes,
            Long maxTaskShuffleReadBytes,
            Long medianTaskShuffleReadBytes,
            Long p95TaskShuffleReadBytes,
            Long p99TaskShuffleReadBytes,
            List<Long> taskShuffleReadBytes,
            long memoryBytesSpilled,
            long diskBytesSpilled,
            Long maxTaskMemoryBytesSpilled,
            Long maxTaskDiskBytesSpilled,
            Long medianTaskMemoryBytesSpilled,
            Long p95TaskMemoryBytesSpilled,
            Long p99TaskMemoryBytesSpilled,
            List<Long> taskMemoryBytesSpilled,
            Long medianTaskDiskBytesSpilled,
            Long p95TaskDiskBytesSpilled,
            Long p99TaskDiskBytesSpilled,
            List<Long> taskDiskBytesSpilled) {
        this(
                id,
                name,
                taskCount,
                completedTasks,
                minTaskDurationMillis,
                maxTaskDurationMillis,
                avgTaskDurationMillis,
                medianTaskDurationMillis,
                p95TaskDurationMillis,
                p99TaskDurationMillis,
                taskDurationMillis,
                0,
                0L,
                List.of(),
                List.of(),
                List.of(),
                shuffleReadBytes,
                maxTaskShuffleReadBytes,
                medianTaskShuffleReadBytes,
                p95TaskShuffleReadBytes,
                p99TaskShuffleReadBytes,
                taskShuffleReadBytes,
                memoryBytesSpilled,
                diskBytesSpilled,
                maxTaskMemoryBytesSpilled,
                maxTaskDiskBytesSpilled,
                medianTaskMemoryBytesSpilled,
                p95TaskMemoryBytesSpilled,
                p99TaskMemoryBytesSpilled,
                taskMemoryBytesSpilled,
                medianTaskDiskBytesSpilled,
                p95TaskDiskBytesSpilled,
                p99TaskDiskBytesSpilled,
                taskDiskBytesSpilled);
    }

    public StageAnalysis(
            int id,
            String name,
            Integer taskCount,
            int completedTasks,
            Long minTaskDurationMillis,
            Long maxTaskDurationMillis,
            Long avgTaskDurationMillis,
            long shuffleReadBytes,
            Long maxTaskShuffleReadBytes) {
        this(
                id,
                name,
                taskCount,
                completedTasks,
                minTaskDurationMillis,
                maxTaskDurationMillis,
                avgTaskDurationMillis,
                null,
                null,
                null,
                List.of(),
                0,
                0L,
                List.of(),
                List.of(),
                List.of(),
                shuffleReadBytes,
                maxTaskShuffleReadBytes,
                null,
                null,
                null,
                List.of(),
                0L,
                0L,
                null,
                null,
                null,
                null,
                null,
                List.of(),
                null,
                null,
                null,
                List.of());
    }
}
